### ISSUE TITLE
Issues about noise scheduler

### ISSUE THREAD

**Issue by Perkins729** [Streaming-Diffusion-Policy/streaming_diffusion_policy#1]
Thank you for your great open-source project; Is there any special design or difference in the newly developed noise scheduler, i.e., diffusion_policy/policy/schedulers.py

**Comment by sigmundhh** [comment]
Hi! Thanks for checking it out

The only difference is that the new scheduler supports a diffusion step on the shape (B, T), not only (B,) as is traditional (e.g., in Diffusion Policy). This can be seen in [this step method](https://github.com/Streaming-Diffusion-Policy/streaming_diffusion_policy/blob/922271ed8c9b09363a6558794ef3cfb1696ea0f1/diffusion_policy/policy/schedulers.py#L249C13-L249C91):

```python
def step(...):
        """
        [...]
        Args:
            [...]
            timestep (B, T), torch.long: current discrete timestep in the diffusion chain.
            [..]
        """
```

Let me know if you have any further questions

**Comment by Perkins729** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I get it now. Thank you for your answers! 
    
        
            
        
    
    
    
    

    

    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Sigmund Hennum ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/24/2024 21:28
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [Streaming-Diffusion-Policy/streaming_diffusion_policy] Issues about noise scheduler (Issue #1)
        
      
    
  
  
Hi! Thanks for checking it out
The only difference is that the new scheduler supports a diffusion step on the shape (B, T), not only (B,) as is traditional (e.g., in Diffusion Policy). This can be seen in this step method:
def step(...):
        """
        [...]
        Args:
            [...]
            timestep (B, T), torch.long: current discrete timestep in the diffusion chain.
            [..]
        """
Let me know if you have any further questions
