### ISSUE TITLE
Request for model checkpoints

### ISSUE THREAD

**Issue by chjchjchjchjchj** [Streaming-Diffusion-Policy/streaming_diffusion_policy#2]
Hello! What an impressive work! Would it be possible to share the trained model checkpoints?

**Comment by sigmundhh** [comment]
Thank you! Sadly, I have not saved the checkpoints, only the experiment logs. However, I believe that having a set of available checkpoints is important, so I'll re-run the SDP experiments and upload them. 
I'll keep this issue open until that is done.

**Comment by sigmundhh** [comment]
Update: All checkpoints except Robomimic Transport are now uploaded to [HuggingFace](https://huggingface.co/sigmundhh/streaming_diffusion_policy). I'll close the issue when Transport is uploaded, too, but I wanted to let you know :)

**Comment by chjchjchjchjchj** [comment]
Thank a lot!

Sigmund Hennum Høeg ***@***.***> 于2024年11月25日周一 17:50写道：

**Comment by chjchjchjchjchj** [comment]
Thanks a lot!

**Comment by sigmundhh** [comment]
The Robomimic Transport checkpoints are now uploaded!

**Comment by chjchjchjchjchj** [comment]
Thanks!
